### ISSUE TITLE
Species list

### ISSUE THREAD

**Issue by stwiss** [manandearth/hirundia#21]
Need to add species to list:

Barn swallow 
Red rumped swallow

** in general perhaps better to record species with their scientific names ***

**Comment by manandearth** [comment]
Could you please supply the scientific names?

**Comment by stwiss** [comment]
Yes.
Common Swift. Apus apus. Vencejo común.
Pallid swift. Apus pallidus. Vencejo pálido
Barn Swallow. Hirundo rustica. Golondrina común
Red rumped swallow. Cecropis daurica. Golondrina dáurica
House martin. Delichon urbicum. Avión común

I am not yet sure if it is best just to put scientific name... As it is a lot to include scientific name and common name in Spanish and English.

**Comment by manandearth** [comment]
Spanish is added in `feature/5-new-look`
english translation is waiting for https://github.com/manandearth/hirundia-management/issues/10
