### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by stwiss** [manandearth/hirundia#22]
Write in Spanish

**Comment by manandearth** [comment]
What in Spanish? the whole site? 
should it be a choice between languages?
I prefer keeping the core db in english ( the names of the fields) and translation will be done on the page.
Tell me what you think. :smile:

**Comment by stwiss** [comment]
Yes I think that it will be available in both languages.
We can keep the core in English.
But as we are starting this project in Spain it will be best that the data collection (names in fields, drop down menus etc) is available in Spanish.
I will also write to text that will be included in Spanish and English.

**Comment by manandearth** [comment]
WIP in https://github.com/manandearth/hirundia/pull/26

**Comment by manandearth** [comment]
Spanish translated in `feature/5-new-look`.
New issue for more complete solution is in https://github.com/manandearth/hirundia-management/issues/10
